api/urls.py
from django.conf.urls import url
from .import views


app_name = "api"
urlpatterns = [
    url(r'^test/$', views.test, name='test'),
    url(r'^user/data/$', views.userData, name='userdata'),
    url(r'^node/data/$', views.nodeData, name='nodedata'),
    url(r'^donate/data/$', views.donateData, name='donatedata'),
    url(r'^random/port/$', views.change_ss_port, name='changessport'),
    url(r'^gen/invitecode/$', views.gen_invite_code, name='geninvitecode'),
]

django-sspanel/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('shadowsocks.urls', namespace='shadowsocks')),
    url(r'', include('django.contrib.auth.urls')),    
    url(r'^server/', include('ssserver.urls', namespace='ssserver')),
    url(r'^api/', include('api.urls', namespace='api')),
]

shadowsocks/urls.py
from django.conf.urls import url
from .import views


app_name = "shadowsocks"
urlpatterns = [
    # 网站用户面板
    url(r'^$', views.index, name='index'),
    url(r'^sshelp/$', views.sshelp, name='sshelp'),
    url(r'^ssclient/$', views.ssclient, name='ssclient'),
    url(r'^ssinvite/$', views.ssinvite, name='ssinvite'),
    url(r'^passinvite/(?P<invitecode>[\S]+)/$',
        views.pass_invitecode, name='passinvitecode'),
    # 注册/登录
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.Login_view, name='login'),
    url(r'^logout/$', views.Logout_view, name='logout'),
    # 节点
    url(r'^nodeinfo/$', views.nodeinfo, name='nodeinfo'),
    url(r'^trafficlog/$', views.trafficlog, name='trafficlog'),
    # 用户信息
    url(r'^users/userinfo/$', views.userinfo, name='userinfo'),
    url(r'^users/userinfoedit/$', views.userinfo_edit, name='userinfo_edit'),
    url(r'^checkin/$', views.checkin, name='checkin'),
    #  二维码
    url(r'^qrcode/ssr/(?P<node_id>[0-9]+)$',
        views.get_ssr_qrcode, name='ssrqrcode'),
    url(r'^qrcode/ss/(?P<node_id>[0-9]+)$',
        views.get_ss_qrcode, name='ssqrcode'),
    # 捐赠/充值
    url(r'^donate/$', views.donate, name='donate'),
    url(r'^shop/$', views.shop, name='shop'),
    url(r'^purchaselog/$', views.purchaselog, name='purchaselog'),
    url(r'^purchase/(?P<goods_id>[0-9]+)$', views.purchase, name='purchase'),
    url(r'^chargecenter/$', views.chargecenter, name='chargecenter'),
    url(r'^charge/$', views.charge, name='charge'),
    # 公告
    url(r'^announcement/$', views.announcement, name='announcement'),
    # 工单
    url(r'^ticket/$', views.ticket, name='ticket'),
    url(r'^ticket/create/$', views.ticket_create, name='ticket_create'),
    url(r'^ticket/edit/(?P<pk>[0-9]+)$',
        views.ticket_edit, name='ticket_edit'),
    url(r'^ticket/delete/(?P<pk>[0-9]+)$',
        views.ticket_delete, name='ticket_delete'),
    # 推广相关
    url(r'^affiliate/$', views.affiliate, name='affiliate'),
    url(r'^rebate/record/$', views.rebate_record, name='rebate'),

    # 网站后台面板
    url(r'^backend/$', views.backend_index, name='backend_index'),
    # 邀请码相关
    url(r'^backend/invite/$', views.backend_invite, name='backend_invite'),
    url(r'^invite_gen_code/$', views.gen_invite_code, name='geninvitecode'),
    # 节点相关
    url(r'^backend/nodeinfo$', views.backend_node_info, name='backend_node_info'),
    url(r'^backend/node/delete/(?P<node_id>[0-9]+)$',
        views.node_delete, name='node_delete'),
    url(r'^backend/node/edit/(?P<node_id>[0-9]+)$',
        views.node_edit, name='node_edit'),
    url(r'^backend/node/create/$', views.node_create, name='node_create'),
    # 用户相关
    #url(r'^backend/aliveuser/$', views.backend_Aliveuser, name='alive_user'),
    url(r'^backend/userlist/$', views.backend_UserList, name='user_list'),
    url(r'^backend/user/delete/(?P<pk>[0-9]+)$',
        views.user_delete, name='user_delete'),
    url(r'^backend/user/search/$', views.user_search, name='user_search'),
    url(r'^backend/user/status/$', views.user_status, name='user_status'),
    # 商品充值相关
    url(r'^backend/charge/$', views.backend_charge, name='backend_charge'),
    url(r'^backend/shop$', views.backend_shop, name='backend_shop'),
    url(r'^backend/shop/delete/(?P<pk>[0-9]+)$',
        views.good_delete, name='good_delete'),
    url(r'^backend/good/create/$', views.good_create, name='good_create'),
    url(r'^backend/good/edit/(?P<pk>[0-9]+)$',
        views.good_edit, name='good_edit'),
    url(r'^backend/purchase/history/$',
        views.purchase_history, name='purchase_history'),
    # 支付宝当面付相关:
    url(r'^facepay/qrcode/$', views.gen_face_pay_qrcode, name='facepay_qrcode'),
    # 购买处理逻辑
    url(r'^facepay/(?P<out_trade_no>[0-9]+)',
        views.Face_pay_view, name='facepay_view'),
    # 公告管理相关
    url(r'^backend/anno/$', views.backend_anno, name='backend_anno'),
    url(r'^backend/anno/delete/(?P<pk>[0-9]+)$',
        views.anno_delete, name='anno_delete'),
    url(r'^backend/anno/create/$', views.anno_create, name='anno_create'),
    url(r'^backend/anno/edit/(?P<pk>[0-9]+)$',
        views.anno_edit, name='anno_edit'),
    # 工单相关
    url(r'^backend/ticket/$', views.backend_ticket, name='backend_ticket'),
    url(r'^backend/ticket/edit/(?P<pk>[0-9]+)$',
        views.backend_ticketedit, name='backend_ticketedit'),
]

ssserver/urls.py
from django.conf.urls import url
from .import views


app_name = "ssserver"
urlpatterns = [
    url(r'^changesspass/$', views.ChangeSsPass, name='changesspass'),
    url(r'^user/edit/(?P<pk>[0-9]+)$', views.User_edit, name='user_edit'),
    url(r'^changessmethod/$', views.ChangeSsMethod, name='changessmethod'),
    url(r'^changessprotocol/$', views.ChangeSsProtocol, name='changessprotocol'),
    url(r'^changessobfs/$', views.ChangeSsObfs, name='changessobfs'),
    url(r'^test/$', views.testcheck, name='test'),
    url(r'^clean/zombie/user$', views.clean_zombie_user, name='clean_zombie_user'),
]

shadowsocks/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.contrib.auth.hashers import make_password, check_password
from django.core.validators import MaxValueValidator, MinValueValidator
# 自己写的小脚本 用于生成邀请码
from .tools import get_long_random_string, get_short_random_string
from django.conf import settings

import markdown
import datetime
import base64
import time

METHOD_CHOICES = (
    ('aes-256-cfb', 'aes-256-cfb'),
    ('aes-128-ctr', 'aes-128-ctr'),
    ('rc4-md5', 'rc4-md5'),
    ('salsa20', 'salsa20'),
    ('chacha20', 'chacha20'),
    ('none', 'none'),
)

STATUS_CHOICES = (
    ('好用', '好用'),
    ('维护', '维护'),
    ('坏了', '坏了'),
)

PROTOCOL_CHOICES = (
    ('auth_sha1_v4', 'auth_sha1_v4'),
    ('auth_aes128_md5', 'auth_aes128_md5'),
    ('auth_aes128_sha1', 'auth_aes128_sha1'),
    ('auth_chain_a', 'auth_chain_a'),
    ('origin', 'origin'),
)


OBFS_CHOICES = (
    ('plain', 'plain'),
    ('http_simple', 'http_simple'),
    ('http_simple_compatible', 'http_simple_compatible'),
    ('http_post', 'http_post'),
    ('tls1.2_ticket_auth', 'tls1.2_ticket_auth'),
)

# Create your models here.


class User(AbstractUser):
    '''SS账户模型'''

    @classmethod
    def proUser(cls):
        '''付费用户数量'''
        return len(cls.objects.filter(level__gt=0))

    @classmethod
    def userNum(cls):
        '''返回用户总数'''
        return len(cls.objects.all())

    @classmethod
    def todayRegister(cls):
        '''返回今日注册的用户'''
        # 获取今天凌晨的时间
        today = datetime.datetime.combine(
            datetime.date.today(), datetime.time.min)
        return cls.objects.filter(date_joined__gt=today)

    balance = models.DecimalField(
        '余额',
        decimal_places=2,
        max_digits=10,
        default=0,
        editable=True,
        null=True,
        blank=True,
    )

    invitecode = models.CharField(
        '邀请码',
        max_length=40,
    )

    invitecode_num = models.PositiveIntegerField(
        '可生成的邀请码数量',
        default=settings.INVITE_NUM
    )

    invited_by = models.PositiveIntegerField(
        '邀请人id',
        default=1,
    )

    # 最高等级限制为9级，和节点等级绑定
    level = models.PositiveIntegerField(
        '用户等级',
        default=0,
        validators=[
            MaxValueValidator(9),
            MinValueValidator(0),
        ]
    )

    level_expire_time = models.DateTimeField(
        '等级有效期',
        default=timezone.now,
        help_text='等级有效期',
    )

    def __str__(self):
        return self.username

    def get_expire_time(self):
        '''返回等级到期时间'''
        return self.level_expire_time

    class Meta(AbstractUser.Meta):
        verbose_name = '用户'


class Node(models.Model):
    '''线路节点'''

    node_id = models.IntegerField('节点id', unique=True,)

    name = models.CharField('名字', max_length=32,)

    server = models.CharField('服务器IP', max_length=128,)

    method = models.CharField(
        '加密类型', default=settings.DEFAULT_METHOD, max_length=32, choices=METHOD_CHOICES,)

    custom_method = models.SmallIntegerField(
        '自定义加密',
        choices=(
            (0, 0),
            (1, 1)),
        default=0,
    )
    traffic_rate = models.FloatField(
        '流量比例',
        default=1.0
    )

    protocol = models.CharField(
        '协议', default=settings.DEFAULT_PROTOCOL, max_length=32, choices=PROTOCOL_CHOICES,)

    obfs = models.CharField(
        '混淆', default=settings.DEFAULT_OBFS, max_length=32, choices=OBFS_CHOICES,)

    info = models.CharField('节点说明', max_length=1024, blank=True, null=True,)

    status = models.CharField(
        '状态', max_length=32, default='ok', choices=STATUS_CHOICES,)

    level = models.PositiveIntegerField(
        '节点等级',
        default=0,
        validators=[
            MaxValueValidator(9),
            MinValueValidator(0),
        ]
    )

    show = models.CharField(
        '是否显示',
        max_length=32,
        choices=(
            ('显示', '显示'),
            ('不显示', '不显示')),
        default='显示',
    )

    def __str__(self):
        return self.name

    def get_ssr_link(self, ss_user):
        '''返回ssr链接'''
        ssr_password = base64.b64encode(
            bytes(ss_user.password, 'utf8')).decode('ascii')
        ssr_code = '{}:{}:{}:{}:{}:{}'.format(
            self.server, ss_user.port, ss_user.protocol, ss_user.method, ss_user.obfs, ssr_password)
        ssr_pass = base64.b64encode(bytes(ssr_code, 'utf8')).decode('ascii')
        ssr_link = 'ssr://{}'.format(ssr_pass)
        return ssr_link

    def get_ss_link(self, ss_user):
        '''返回ss链接'''
        ss_code = '{}:{}@{}:{}'.format(
            ss_user.method, ss_user.password, self.server, ss_user.port)
        ss_pass = base64.b64encode(bytes(ss_code, 'utf8')).decode('ascii')
        ss_link = 'ss://{}'.format(ss_pass)
        return ss_link

    class Meta:
        ordering = ['id']
        verbose_name_plural = '节点'
        db_table = 'ss_node'


class NodeInfoLog(models.Model):
    '''节点负载记录'''

    node_id = models.IntegerField('节点id', blank=False, null=False)

    uptime = models.FloatField('更新时间', blank=False, null=False)

    load = models.CharField('负载', max_length=32, blank=False, null=False)

    log_time = models.IntegerField('日志时间', blank=False, null=False)

    def __str__(self):
        return str(self.node_id)

    class Meta:
        verbose_name_plural = '节点日志'
        db_table = 'ss_node_info_log'
        ordering = ('-log_time',)


class NodeOnlineLog(models.Model):
    '''节点在线记录'''

    @classmethod
    def totalOnlineUser(cls):
        '''返回所有节点的在线人数总和'''
        return sum([o.get_online_user() for o in cls.objects.all()])

    node_id = models.IntegerField('节点id', blank=False, null=False)

    online_user = models.IntegerField('在线人数', blank=False, null=False)

    log_time = models.IntegerField('日志时间', blank=False, null=False)

    def __str__(self):
        return '节点：{}'.format(self.node_id)

    def get_oneline_status(self):
        '''检测是否在线'''
        if int(time.time()) - self.log_time > 75:
            return False
        else:
            return True

    def get_online_user(self):
        '''返回在线人数'''
        if self.get_oneline_status() == True:
            return self.online_user
        else:
            return 0

    class Meta:
        verbose_name_plural = '节点在线记录'
        db_table = 'ss_node_online_log'


class InviteCode(models.Model):
    '''邀请码'''

    type = models.IntegerField(
        '类型',
        choices=((1, '公开'), (0, '不公开')),
        default=0,
    )

    code_id = models.PositiveIntegerField(
        '邀请人ID',
        default=1,
    )

    code = models.CharField(
        '邀请码',
        primary_key=True,
        blank=True,
        max_length=40,
        default=get_long_random_string
    )

    time_created = models.DateTimeField(
        '创建时间',
        editable=False,
        auto_now_add=True
    )

    isused = models.BooleanField(
        '是否使用',
        default=False,
    )

    def __str__(self):
        return str(self.code)

    class Meta:
        verbose_name_plural = '邀请码'
        ordering = ('isused', '-time_created',)


class RebateRecord(models.Model):
    '''返利记录'''

    user_id = models.PositiveIntegerField(
        '返利人ID',
        default=1,
    )

    money = models.DecimalField(
        '金额',
        decimal_places=2,
        max_digits=10,
        default=0,
        null=True,
        blank=True,
    )

    rebatetime = models.DateTimeField(
        '返利时间',
        editable=False,
        auto_now_add=True
    )


class Aliveip(models.Model):
    '''节点在线ip'''

    node_id = models.ForeignKey(
        Node,
        related_name='alive_node_id',
        on_delete=models.CASCADE,
        blank=True, null=True
    )

    user_name = models.CharField(
        '用户名',
        max_length=50,
        blank=True, null=True)

    ip_address = models.GenericIPAddressField('在线ip')

    local = models.CharField(
        '归属地',
        max_length=128,
        blank=True, null=True
    )
    time = models.DateTimeField(
        '时间',
        editable=False,
        auto_now_add=True
    )

    def __str__(self):
        return self.ip_address

    class Meta:
        verbose_name_plural = '在线ip'
        ordering = ('-time',)


class Donate(models.Model):

    @classmethod
    def totalDonateMoney(cls):
        '''返回捐赠总金额'''
        return sum([d.money for d in cls.objects.all()])

    @classmethod
    def totalDonateNums(cls):
        '''返回捐赠总数量'''
        return len(cls.objects.all())

    @classmethod
    def richPeople(cls):
        '''返回捐赠金额最多的前10名'''
        rec = {}
        for d in cls.objects.all():
            if d.user not in rec.keys():
                rec[d.user] = d.money
            else:
                rec[d.user] += d.money
        return sorted(rec.items(), key=lambda rec: rec[1], reverse=True)[:10]

    '''捐赠记录'''
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )

    time = models.DateTimeField(
        '捐赠时间',
        editable=False,
        auto_now_add=True
    )

    money = models.DecimalField(
        '捐赠金额',
        decimal_places=2,
        max_digits=10,
        default=0,
        null=True,
        blank=True,
    )

    def __str__(self):
        return str(self.money)

    class Meta:
        verbose_name_plural = '捐赠'
        ordering = ('-time',)


class MoneyCode(models.Model):
    '''充值码'''
    user = models.CharField(
        '用户名',
        max_length=128,
        blank=True,
        null=True,
    )

    time = models.DateTimeField(
        '捐赠时间',
        editable=False,
        auto_now_add=True
    )

    code = models.CharField(
        '充值码',
        unique=True,
        blank=True,
        max_length=40,
        default=get_long_random_string
    )

    number = models.DecimalField(
        '捐赠金额',
        decimal_places=2,
        max_digits=10,
        default=10,
        null=True,
        blank=True,
    )

    isused = models.BooleanField(
        '是否使用',

templates/backend/annolist.html
{% extends 'backendbase.html' %} {% block main %}


<div class="column is-12">
    <section class="hero is-light is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    公告列表：
                </h1>
                <h2 class="subtitle">
                    领导请下放通知!
                </h2>
            </div>
        </div>
    </section>
</div>

<div class="column is-12">
    <div class="box">

        <table class="table is-fullwidth">
            <thead>
                <tr>
                    <th>操作:</th>
                    <th>ID:</th>
                    <th>日期</th>
                    <th>内容:</th>
                </tr>
            </thead>
            {% for rec in anno %}
            <tr>
                <td>
                    <p class="control">
                        <a class="button is-info" href="{% url 'shadowsocks:anno_edit' rec.pk %}">编辑</a>
                    </p>
                    <p class="control">
                        <a class="button is-danger modal-button" data-target="modal-{{ rec.pk }}">删除</a>
                    </p>
                </td>
                <td>#{{ rec.pk}}</td>
                <td>{{ rec.time }}</td>
                <td>{{ rec.body |safe }}</td>
            </tr>

            <div class="modal user_delete" id="modal-{{ rec.pk }}">
                <div class="modal-background"></div>
                <div class="modal-card">
                    <header class="modal-card-head">
                        <p class="modal-card-title">ID:{{ rec.pk }}</p>
                        <button class="delete"></button>
                    </header>
                    <section class="modal-card-body">
                        <p class="subtitle">确定要删除:<code>{{ rec.pk }}</code>号公告么?</p>
                        <p align="center">
                            <a class="button is-danger is-outlined" href="{% url 'shadowsocks:anno_delete' rec.pk %}">确定删除</a>
                        </p>
                    </section>
                </div>
            </div>
            {% empty %}
            <p class="subtitle">没有公告哟</p>
            {% endfor %}
        </table>
        <p align="right"><a class="button is-danger is-outlined" href="{% url 'shadowsocks:anno_create' %}">增加公告</a></p>
        </div>
</div>

{% endblock main %}

templates/backend/index.html
{% extends 'backendbase.html' %} {% block main %}


<div class="column is-12">
    <section class="hero is-light is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    汇总：
                </h1>
                <h2 class="subtitle">
                    下面是系统运行状态简报：
                </h2>
            </div>
        </div>
    </section>
</div>

<div class="column is-12">
    <div class="tile is-ancestor">
        <div class="tile is-6 is-vertical is-parent">
            <div class="tile is-child box">
                <canvas id="userState" width="auto" height="300"></canvas>
            </div>
        </div>
        <div class="tile is-6 is-vertical is-parent">
            <div class="tile is-child box">
                <canvas id="nodeState"></canvas>
            </div>
            <div class="tile is-child box">
                <canvas id="donateState"></canvas>
            </div>
        </div>
    </div>
</div>

<script>
    // 获取后台首页状态
    var getSystemStatus = function () {
        $.getJSON("{% url 'api:userdata' %}", function (results) {
            genDoughnutChart('userState', '总用户:{{ userNum }} ', ['在线人数','今日注册', '今日签到', '从未签到', '从未使用'], results)
        })

        $.getJSON("{% url 'api:nodedata' %}", function (results) {
            genDoughnutChart('nodeState', '节点流量 单位：GB', results.nodeName, results.nodeTraffic)
        })

        $.getJSON("{% url 'api:donatedata' %}", function (results) {
            genDoughnutChart('donateState', '收入分析', ['成交数 (笔)', '成交金额 (元)'], results)
        })
    }
    getSystemStatus()
</script> {% endblock main %}

templates/backend/invitecode.html
{% extends 'backendbase.html' %} {% block main %} {% load ehcofilter %}

<div class="column is-12">
    <section class="hero is-light is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    邀请码管理：
                </h1>
                <h2 class="subtitle">
                    添加邀请码...
                </h2>
            </div>
        </div>
    </section>
</div>



<div class="column is-12">
    <div class="box">
        <form method="get" action="{% url 'shadowsocks:geninvitecode' %}">
            <div class="field has-addons">
                <div class="control">
                    <input name="num" class="input" placeholder="键入邀请码数量" required>
                </div>
                <div class="control">
                    <div class="select">
                        <select name="type">
                      <option value=1>公开显示</option>
                      <option value=0>不公开显示</option>
                    </select>
                    </div>
                </div>
                <div class="control">
                    <button type="submit" class="button is-outlined is-info">添加</button>
                </div>
            </div>
        </form>
    </div>

    <div class="box">
        <p class="subtitle">不公开显示的邀请码列表</p>
        <br>
        <table class="table is-fullwidth">
            <thead>
                <tr>
                    <th>类型:</th>
                    <th>代码:</th>
                    <th>创建时间</th>
                </tr>
            </thead>
            {% for code in code_list %}
            <tr>
                <td>{{ code.get_type_display }}</td>
                <td>{{ code.code }}</td>
                <td>{{ code.time_created }}</td>
            </tr>
            {% empty %}
            <p class="subtitle">没有私密的邀请码</p>
            {% endfor %}
        </table>
    </div>
</div>

</div>

{% endblock main %}

templates/backend/shop.html
{% extends 'backendbase.html' %} {% block main %}


<div class="column is-12">
    <section class="hero is-light is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    商品列表：
                </h1>
                <h2 class="subtitle">
                    添加或者删除商品：
                </h2>
            </div>
        </div>
    </section>
</div>

<div class="column is-12">
    <div class="box">
        <table class="table is-fullwidth">
            <thead>
                <tr>
                    <th>操作:</th>
                    <th>ID:</th>
                    <th>商品描述:</th>
                    <th>金额:</th>
                    <th>流量:</th>
                    <th>等级:</th>
                </tr>
            </thead>

            {% for good in goods %}
            <tr>
                <td>
                    <p class="control">
                        <a class="button is-info" href="{% url 'shadowsocks:good_edit' good.pk  %}">编辑</a>
                    </p>
                    <p class="control">
                        <a class="button is-danger modal-button" data-target="modal-{{ good.pk }}">删除</a>
                    </p>
                </td>

                <td>#{{ good.pk }}</td>
                <td>{{ good.name }}</td>
                <td>{{ good.money }}</td>
                <td>{{ good.get_transfer_by_GB }} GB </td>
                <td>{{ good.level }}</td>
            </tr>


            <div class="modal node_delete" id="modal-{{ good.pk }}">
                <div class="modal-background"></div>
                <div class="modal-card">
                    <header class="modal-card-head">
                        <p class="modal-card-title">商品名:{{ good.name }}</p>
                        <button class="delete"></button>
                    </header>
                    <section class="modal-card-body">
                        <p class="subtitle">确定要删除:<code>{{ good.name }}</code>?</p>                        
                        <p align="center">
                            <a class="button is-danger is-outlined" href="{% url 'shadowsocks:good_delete' good.pk %}">确定删除</a>
                        </p>
                    </section>
                </div>
            </div>

            {% empty %}
            <h2 class="subtitle">
                暂时没有商品，点击下方按钮添加商品
            </h2>
            {% endfor %}
        </table>
        <p align="right"><a class="button is-danger is-outlined" href="{% url 'shadowsocks:good_create' %}">增加商品</a></p>

    </div>

</div>



{% endblock main %}

templates/backend/userlist.html
 {% extends 'backendbase.html' %} {% block main %}


<div class="column is-12">
    <section class="hero is-light is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    用户列表：
                </h1>
                <h2 class="subtitle">
                    给衣食父母们请安了!
                </h2>
            </div>
        </div>
    </section>
</div>

<div class="column is-12">

    <form method="get" action="{% url 'shadowsocks:user_search' %}">
        <div class="field has-addons">
            <div class="control">
                <input name="q" class="input" type="search" placeholder="用户名/邮箱 模糊搜索" required>
            </div>
            <div class="control">
                <button type="submit" class="button is-outlined is-info">搜索</button>
            </div>
        </div>
    </form>
    <br>
    <div class="box">
        <nav class="pagination">
            {% if contacts.has_previous %}
            <a class="pagination-previous" href="?page={{ contacts.previous_page_number }}">上一页</a> {% endif %} {% if contacts.has_next%}
            <a class="pagination-next" href="?page={{ contacts.next_page_number }}">下一页</a> {% endif %}
            <p>页码：</p>
            <ul class="pagination-list">
                {% if first %}
                <a href="?page=1" class="pagination-link">1</a> {% endif %} {% if left %} {% if left_has_more %}
                <span>...</span> {% endif %} {% for i in left %}
                <a href="?page={{ i }}" class="pagination-link">{{ i }}</a> {% endfor %} {% endif %}
                <a href="?page={{ page }}" class="pagination-link is-current">{{ page }}</a> {% if right %} {% for i in right%}
                <a href="?page={{ i }}" class="pagination-link">{{ i }}</a> {% endfor %} {% if right_has_more %}
                <span>...</span> {% endif %} {% endif %} {% if last %}
                <a href="?page={{ total }}" class="pagination-link">{{ total }}</a> {% endif %}
            </ul>
        </nav>
        <br>

        <table class="table is-fullwidth">
            <thead>
                <tr>
                    <th>操作:</th>
                    <th>ID:</th>
                    <th>用户名</th>
                    <th>邮箱:</th>
                    <th>端口:</th>
                    <th>已用/总流量</th>
                </tr>
            </thead>
            {% for contact in contacts %}
            <tr>
                <td>
                    <p class="control">
                        <a class="button is-info" href="{% url 'ssserver:user_edit' contact.ss_user.pk %}">编辑</a>
                    </p>
                    <p class="control">
                        <a class="button is-danger modal-button" data-target="modal-{{ contact.pk }}">删除</a>
                    </p>
                </td>
                <td>#{{ contact.pk}}</td>
                <td>{{ contact.username }}</td>
                <td>{{ contact.email }}</td>
                <td>{{ contact.ss_user.port }}</td>
                <td>{{ contact.ss_user.get_traffic }} GB / {{ contact.ss_user.get_transfer }} GB</td>
            </tr>

            <div class="modal user_delete" id="modal-{{ contact.pk }}">
                <div class="modal-background"></div>
                <div class="modal-card">
                    <header class="modal-card-head">
                        <p class="modal-card-title">用户名:{{ contact.username }}</p>
                        <button class="delete"></button>
                    </header>
                    <section class="modal-card-body">
                        <p class="subtitle">确定要删除:<code>{{ contact.username }}</code>?</p>
                        <p align="center">
                            <a class="button is-danger is-outlined" href="{% url 'shadowsocks:user_delete' contact.pk %}">确定删除</a>
                        </p>
                    </section>
                </div>
            </div>
            {% empty %}
            <p class="subtitle">没有用户哟</p>
            {% endfor %}

        </table>


    </div>

</div>

{% endblock main %}