api/urls.py
from django.conf.urls import url
from .import views


app_name = "api"
urlpatterns = [
    url(r'^test/$', views.test, name='test'),
    url(r'^user/data/$', views.userData, name='userdata'),
    url(r'^node/data/$', views.nodeData, name='nodedata'),
    url(r'^donate/data/$', views.donateData, name='donatedata'),
    url(r'^random/port/$', views.change_ss_port, name='changessport'),
    url(r'^gen/invitecode/$', views.gen_invite_code, name='geninvitecode'),
]

django-sspanel/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('shadowsocks.urls', namespace='shadowsocks')),
    url(r'', include('django.contrib.auth.urls')),    
    url(r'^server/', include('ssserver.urls', namespace='ssserver')),
    url(r'^api/', include('api.urls', namespace='api')),
]

shadowsocks/urls.py
from django.conf.urls import url
from .import views


app_name = "shadowsocks"
urlpatterns = [
    # 网站用户面板
    url(r'^$', views.index, name='index'),
    url(r'^sshelp/$', views.sshelp, name='sshelp'),
    url(r'^ssclient/$', views.ssclient, name='ssclient'),
    url(r'^ssinvite/$', views.ssinvite, name='ssinvite'),
    url(r'^passinvite/(?P<invitecode>[\S]+)/$',
        views.pass_invitecode, name='passinvitecode'),
    # 注册/登录
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.Login_view, name='login'),
    url(r'^logout/$', views.Logout_view, name='logout'),
    # 节点
    url(r'^nodeinfo/$', views.nodeinfo, name='nodeinfo'),
    url(r'^trafficlog/$', views.trafficlog, name='trafficlog'),
    # 用户信息
    url(r'^users/userinfo/$', views.userinfo, name='userinfo'),
    url(r'^users/userinfoedit/$', views.userinfo_edit, name='userinfo_edit'),
    url(r'^checkin/$', views.checkin, name='checkin'),
    #  二维码
    url(r'^qrcode/ssr/(?P<node_id>[0-9]+)$',
        views.get_ssr_qrcode, name='ssrqrcode'),
    url(r'^qrcode/ss/(?P<node_id>[0-9]+)$',
        views.get_ss_qrcode, name='ssqrcode'),
    # 捐赠/充值
    url(r'^donate/$', views.donate, name='donate'),
    url(r'^shop/$', views.shop, name='shop'),
    url(r'^purchaselog/$', views.purchaselog, name='purchaselog'),
    url(r'^purchase/(?P<goods_id>[0-9]+)$', views.purchase, name='purchase'),
    url(r'^chargecenter/$', views.chargecenter, name='chargecenter'),
    url(r'^charge/$', views.charge, name='charge'),
    # 公告
    url(r'^announcement/$', views.announcement, name='announcement'),
    # 工单
    url(r'^ticket/$', views.ticket, name='ticket'),
    url(r'^ticket/create/$', views.ticket_create, name='ticket_create'),
    url(r'^ticket/edit/(?P<pk>[0-9]+)$',
        views.ticket_edit, name='ticket_edit'),
    url(r'^ticket/delete/(?P<pk>[0-9]+)$',
        views.ticket_delete, name='ticket_delete'),
    # 推广相关
    url(r'^affiliate/$', views.affiliate, name='affiliate'),
    url(r'^rebate/record/$', views.rebate_record, name='rebate'),

    # 网站后台面板
    url(r'^backend/$', views.backend_index, name='backend_index'),
    # 邀请码相关
    url(r'^backend/invite/$', views.backend_invite, name='backend_invite'),
    url(r'^invite_gen_code/$', views.gen_invite_code, name='geninvitecode'),
    # 节点相关
    url(r'^backend/nodeinfo$', views.backend_node_info, name='backend_node_info'),
    url(r'^backend/node/delete/(?P<node_id>[0-9]+)$',
        views.node_delete, name='node_delete'),
    url(r'^backend/node/edit/(?P<node_id>[0-9]+)$',
        views.node_edit, name='node_edit'),
    url(r'^backend/node/create/$', views.node_create, name='node_create'),
    # 用户相关
    #url(r'^backend/aliveuser/$', views.backend_Aliveuser, name='alive_user'),
    url(r'^backend/userlist/$', views.backend_UserList, name='user_list'),
    url(r'^backend/user/delete/(?P<pk>[0-9]+)$',
        views.user_delete, name='user_delete'),
    url(r'^backend/user/search/$', views.user_search, name='user_search'),
    url(r'^backend/user/status/$', views.user_status, name='user_status'),
    # 商品充值相关
    url(r'^backend/charge/$', views.backend_charge, name='backend_charge'),
    url(r'^backend/shop$', views.backend_shop, name='backend_shop'),
    url(r'^backend/shop/delete/(?P<pk>[0-9]+)$',
        views.good_delete, name='good_delete'),
    url(r'^backend/good/create/$', views.good_create, name='good_create'),
    url(r'^backend/good/edit/(?P<pk>[0-9]+)$',
        views.good_edit, name='good_edit'),
    url(r'^backend/purchase/history/$',
        views.purchase_history, name='purchase_history'),
    # 支付宝当面付相关:
    url(r'^facepay/qrcode/$', views.gen_face_pay_qrcode, name='facepay_qrcode'),
    # 购买处理逻辑
    url(r'^facepay/(?P<out_trade_no>[0-9]+)',
        views.Face_pay_view, name='facepay_view'),
    # 公告管理相关
    url(r'^backend/anno/$', views.backend_anno, name='backend_anno'),
    url(r'^backend/anno/delete/(?P<pk>[0-9]+)$',
        views.anno_delete, name='anno_delete'),
    url(r'^backend/anno/create/$', views.anno_create, name='anno_create'),
    url(r'^backend/anno/edit/(?P<pk>[0-9]+)$',
        views.anno_edit, name='anno_edit'),
    # 工单相关
    url(r'^backend/ticket/$', views.backend_ticket, name='backend_ticket'),
    url(r'^backend/ticket/edit/(?P<pk>[0-9]+)$',
        views.backend_ticketedit, name='backend_ticketedit'),
]

templates/backendbase.html
{% load ehcofilter %}
<!DOCTYPE html>
<html lang="zh">

<head>
    {% load staticfiles %}
    <title>{% settings_value "TITLE" %}</title>
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href=" {% static 'img/logo/logo.ico' %}" />
    <!-- css -->
    <link rel="stylesheet" href="{% static 'sspanel/css/bulma.css'%}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'sspanel/css/ehco.css'%}">
    <link rel="stylesheet" href="{% static 'sspanel/css/sweetalert.css'%}">
    <!-- js -->
    <script src="{% static 'sspanel/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'sspanel/js/sweetalert.min.js' %}"></script>
    <script src="{% static 'sspanel/js/ehco.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.bundle.min.js"></script>

</head>

<body>
    <nav class="navbar is-primary">
        <div class="navbar-brand">
            <a class="navbar-item" href="/">
                <img src="{% static 'img/logo/logo.png' %}" alt="谜之屋logo">
            </a>
            <div class="navbar-burger burger" data-target="navMenuColorprimary-example">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div id="navMenuColorprimary-example" class="navbar-menu">
            <div class="navbar-end">
                <a class="navbar-item is-hidden-mobile" href="/">首页</a>
                <a class="navbar-item is-hidden-mobile" href="/sshelp">使用说明</a>
                <a class="navbar-item is-hidden-mobile" href="/ssinvite">邀请码</a>
                <a class="navbar-item is-hidden-mobile" href="/ssclient">客户端</a>
                <div class="navbar-item has-dropdown is-hoverable is-hidden-mobile">
                    <span class="navbar-item">
                        <a class="button is-primary is-inverted" href="{% url 'shadowsocks:userinfo' %}">
                            <span class="icon">
                                <i class="fa fa-user-circle"></i>
                            </span>
                            <span>{{ user.username }}</span>
                        </a>
                    </span>
                    <div class="navbar-dropdown">
                        <a class="navbar-item" href="{% url 'shadowsocks:userinfo' %}">
                            <span class="icon">
                                <i class="fa fa-users"></i>
                            </span>
                            <span>用户中心</span>
                        </a>
                        <hr class="navbar-divider">
                        <a class="navbar-item" href="{% url 'shadowsocks:logout' %}">
                            <span class="icon">
                                <i class="fa fa-sign-out"></i>
                            </span>
                            <span>注销登录</span>
                        </a>
                    </div>
                </div>
                <!-- 手机界面菜单-->
                <div class="is-hidden-tablet">
                    <a class="navbar-item is-active" href="{% url 'shadowsocks:backend_index' %}">系统状态</a>
                    <a class="navbar-item" href="{% url 'shadowsocks:backend_invite' %}">邀请相关</a>
                    <a class="navbar-item" href="{% url 'shadowsocks:backend_anno' %}">公告管理</a>
                    <a class="navbar-item" href="{% url 'shadowsocks:backend_ticket' %}">工单管理</a>
                    <a class="navbar-item is-active" href="{% url 'shadowsocks:backend_node_info' %}">节点列表</a>
                    <a class="navbar-item is-active" href="{% url 'shadowsocks:backend_charge' %}">充值管理</a>
                    <a class="navbar-item" href="{% url 'shadowsocks:backend_shop' %}">商品管理</a>
                    <a class="navbar-item" href="{% url 'shadowsocks:purchase_history' %}">购买记录</a>
                    <a class="navbar-item" href="{% url 'shadowsocks:user_list' %}">用户列表</a>
                    <a class="navbar-item" href="{% url 'shadowsocks:user_status' %}">用户分析</a>                    
                    <a class="navbar-item is-active" href="/admin">数据后台</a>
                    <a class="navbar-item" href="{% url 'shadowsocks:userinfo' %}">用户面板</a>
                </div>
            </div>
        </div>
    </nav>
    <section class="hero is-small is-primary ">
        <!-- Hero content: will be in the middle -->
        <div class="hero-body">
            <div class="container has-text-centered">
                <h1 class="title">
                    <a href="/">
                        <strong>{% settings_value "SUBTITLE" %}</strong>
                    </a>
                </h1>
                <h2 class="subtitle">
                    你说会发现什么呢？
                </h2>
            </div>
        </div>
    </section>
    <br/>
    <div class="container is-fluid">
        <div class="columns">
            <div class="column is-2 is-hidden-mobile">
                <div class="box">
                    {% if user.is_authenticated %}
                    <aside class="menu">
                        <p class="menu-label">
                            管理面板：
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'shadowsocks:backend_index' %}">系统状态</a>
                            </li>
                            <li>
                                <a href="{% url 'shadowsocks:backend_invite' %}">邀请相关</a>
                            </li>
                            <li>
                                <a href="{% url 'shadowsocks:backend_anno' %}">公告管理</a>
                            </li>
                            <li>
                                <a href="{% url 'shadowsocks:backend_ticket' %}">工单管理</a>
                            </li>
                        </ul>
                        <p class="menu-label">
                            节点相关
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'shadowsocks:backend_node_info' %}">节点列表</a>
                            </li>
                        </ul>
                        <p class="menu-label">
                            交易相关
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'shadowsocks:backend_charge' %}">充值管理</a>
                            </li>
                            <li>
                                <a href="{% url 'shadowsocks:backend_shop' %}">商品管理</a>
                            </li>
                            <li>
                                <a href="{% url 'shadowsocks:purchase_history' %}">购买记录</a>
                            </li>
                        </ul>
                        <p class="menu-label">
                            用户相关
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'shadowsocks:user_list' %}">用户列表</a>
                            </li>
                            <li>
                                <a href="{% url 'shadowsocks:user_status' %}">用户分析</a>
                            </li>
                        </ul>
                        <p class="menu-label">
                            面板跳转
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="/admin">数据后台</a>
                            </li>
                        </ul>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'shadowsocks:userinfo' %}">用户面板</a>
                            </li>
                        </ul>
                        {% endif %}
                    </aside>
                </div>
            </div>

            <div class="column is-10">

                {% block main %} {% endblock main%}

            </div>
        </div>
    </div>

    <footer>
        <div class="container">
            <div class="content has-text-centered">
                <p>
                    <p class="copyright">&copy; 2017·公众号: findyourownway·
                        <a href="https://github.com/ehco1996">GitHub</a>·
                        <a href="https://www.zhihu.com/people/Ehcostuff/activities">知乎</a>
                    </p>
                </p>
            </div>
        </div>
    </footer>
</body>

<!--整站消息提醒功能 -->
{% if registerinfo %}
<script>
    swal("{{ registerinfo.title }}", '{{ registerinfo.subtitle }}', '{{ registerinfo.status }}');

</script> {% endif %}

</html>

templates/base.html
{% load ehcofilter %}
<!DOCTYPE html>
<html lang="zh">

<head>
    {% load staticfiles %}
    <title>{% settings_value "TITLE" %}</title>
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'img/logo/logo.ico' %}" />
    <!-- css -->
    <link rel="stylesheet" href="{% static 'sspanel/css/bulma.css'%}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'sspanel/css/ehco.css'%}">
    <link rel="stylesheet" href="{% static 'sspanel/css/sweetalert.css'%}">
    <!-- js -->
    <script src="{% static 'sspanel/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'sspanel/js/sweetalert.min.js' %}"></script>
    <script src="{% static 'sspanel/js/ehco.js' %}"></script>
</head>

<body>
    <nav class="navbar is-info">
        <div class="navbar-brand">
            <a class="navbar-item" href="/">
                <img src="{% static 'img/logo/logo.png' %}" alt="谜之屋logo" width="112" height="28">
            </a>
            <div class="navbar-burger burger" data-target="navMenuColorprimary-example">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div id="navMenuColorprimary-example" class="navbar-menu">
            <div class="navbar-end">
                <a class="navbar-item" href="/">首页</a>
                <a class="navbar-item" href="/sshelp">使用说明</a>
                <a class="navbar-item" href="/ssinvite">邀请码</a>
                {% if user.is_authenticated %}
                <a class="navbar-item" href="/ssclient">客户端</a>
                <div class="navbar-item has-dropdown is-hoverable is-hidden-mobile">
                    <span class="navbar-item">
                        <a class="button is-info is-inverted" href="{% url 'shadowsocks:userinfo' %}">
                            <span class="icon">
                                <i class="fa fa-user-circle"></i>
                            </span>
                            <span>{{ user.username }}</span>
                        </a>
                    </span>
                    <div class="navbar-dropdown">
                        <a class="navbar-item" href="{% url 'shadowsocks:userinfo' %}">
                            <span class="icon">
                                <i class="fa fa-users"></i>
                            </span>
                            <span>用户中心</span>
                        </a>
                        <hr class="navbar-divider">
                        <a class="navbar-item" href="{% url 'shadowsocks:logout' %}">
                            <span class="icon">
                                <i class="fa fa-sign-out"></i>
                            </span>
                            <span>注销登录</span>
                        </a>
                    </div>
                </div>
                <!-- 手机界面菜单-->
                <div class="is-hidden-tablet">
                    <a class="navbar-item is-active" href="{% url 'shadowsocks:userinfo' %}">账户信息</a>
                    <a class="navbar-item" href="{% url 'shadowsocks:userinfo_edit' %}">节点编辑</a>
                    <a class="navbar-item" href="{% url 'shadowsocks:donate' %}">捐赠付费</a>
                    <a class="navbar-item" href="{% url 'shadowsocks:announcement' %}">公告栏</a>
                    <a class="navbar-item is-active" href="{% url 'shadowsocks:nodeinfo' %}">节点信息</a>
                    <a class="navbar-item" href="{% url 'shadowsocks:trafficlog' %}">流量记录</a>
                    <a class="navbar-item" href="{% url 'shadowsocks:ticket' %}">工单系统</a>
                    <a class="navbar-item is-active" href="{% url 'shadowsocks:chargecenter' %}">充值界面</a>
                    <a class="navbar-item" href="{% url 'shadowsocks:shop' %}">商品界面</a>
                    <a class="navbar-item" href="{% url 'shadowsocks:purchaselog' %}">购买记录</a>
                    <a class="navbar-item is-active" href="{% url 'shadowsocks:affiliate' %}">邀请管理</a>
                    <a class="navbar-item" href="{% url 'shadowsocks:rebate' %}">返利记录</a>
                    {% if perms.shadowsocks %}
                    <a class="navbar-item is-active" href="/admin">数据后台</a>
                    <a class="navbar-item" href="{% url 'shadowsocks:backend_index' %}">网站后台</a>
                    {% endif %}
                </div>
                {% endif %}
            </div>
        </div>
    </nav>
    <section class="hero is-small is-info">
        <div class="hero-body">
            <div class="container has-text-centered">
                <h1 class="title">
                    <a href="/">
                        <strong>{% settings_value "SUBTITLE" %}</strong>
                    </a>
                </h1>
                <h2 class="subtitle">
                    你说会发现什么呢？
                </h2>
            </div>
        </div>
    </section>
    <br/>
    <div class="container is-fluid">
        <div class="columns">
            <div class="column is-2 is-hidden-mobile">
                <div class="box">
                    {% if user.is_authenticated %}
                    <aside class="menu">
                        <p class="menu-label">
                            我的信息：
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a class="" href="{% url 'shadowsocks:userinfo' %}">账户信息</a>
                            </li>
                            <li>
                                <a href="{% url 'shadowsocks:userinfo_edit' %}">节点编辑</a>
                            </li>
                            <li>
                                <a href="{% url 'shadowsocks:donate' %}">捐赠付费</a>
                            </li>
                            <li>
                                <a href="{% url 'shadowsocks:announcement' %}">查看公告</a>
                            </li>
                        </ul>
                        <p class="menu-label">
                            使用菜单
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'shadowsocks:nodeinfo' %}">节点信息</a>
                            </li>
                            <li>
                                <a href="{% url 'shadowsocks:trafficlog' %}">流量记录</a>
                            </li>
                            <li>
                                <a href="{% url 'shadowsocks:ticket' %}">工单系统</a>
                            </li>
                        </ul>
                        <p class="menu-label">
                            交易系统
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'shadowsocks:chargecenter' %}">充值界面</a>
                            </li>
                            <li>
                                <a href="{% url 'shadowsocks:shop' %}">商品界面</a>
                            </li>
                            <li>
                                <a href="{% url 'shadowsocks:purchaselog' %}">购买记录</a>
                            </li>
                        </ul>
                        <p class="menu-label">
                            邀请系统
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'shadowsocks:affiliate' %}">邀请管理</a>
                            </li>
                            <li>
                                <a href="{% url 'shadowsocks:rebate' %}">返利记录</a>
                            </li>
                        </ul>

                        {% if perms.shadowsocks %}
                        <p class="menu-label">
                            管理面板
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="/admin">数据后台</a>
                            </li>
                        </ul>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'shadowsocks:backend_index' %}">网站后台</a>
                            </li>
                        </ul>
                        {% endif %} {% else %}
                        <article class="message is-primary">
                            <div class="message-header">
                                <p>幻想乡：</p>
                                <button class="delete"></button>
                            </div>
                            <div class="message-body">
                                幻想中的:「地方」
                            </div>
                        </article>
                        <article class="message is-info">
                            <div class="message-header">
                                <p>谜の屋：</p>
                                <button class="delete"></button>
                            </div>
                            <div class="message-body">
                                他不存于:「地表」
                            </div>
                        </article>
                        <article class="message is-success">
                            <div class="message-header">
                                <p>时之塔：</p>
                                <button class="delete"></button>
                            </div>
                            <div class="message-body">
                                这囚禁着：「思想」
                            </div>
                        </article>
                        <article class="message is-warning">
                            <div class="message-header">
                                <p>旧の桥</p>
                                <button class="delete"></button>
                            </div>
                            <div class="message-body">
                                却连接着：「自由」
                            </div>
                        </article>
                        {% endif %}
                    </aside>
                </div>
            </div>

            <div class="column is-10">

                {% block main %} {% endblock main%}

            </div>
        </div>
    </div>

    <footer>
        <div class="container">
            <div class="content has-text-centered">
                <p>
                    <p class="copyright">&copy; 2017·公众号: findyourownway·
                        <a href="https://github.com/ehco1996">GitHub</a>·
                        <a href="https://www.zhihu.com/people/Ehcostuff/activities">知乎</a>
                    </p>
                </p>
            </div>
        </div>
    </footer>
</body>
<!--整站消息提醒功能 -->
{% if registerinfo %}
<script>
    swal("{{ registerinfo.title }}", '{{ registerinfo.subtitle }}', '{{ registerinfo.status }}');
</script> {% endif %}

</html>