api/urls.py
from django.conf.urls import url
from .import views


app_name = "api"
urlpatterns = [
    url(r'^test/$', views.test, name='test'),
    url(r'^user/data/$', views.userData, name='userdata'),
    url(r'^node/data/$', views.nodeData, name='nodedata'),
    url(r'^donate/data/$', views.donateData, name='donatedata'),
    url(r'^random/port/$', views.change_ss_port, name='changessport'),
    url(r'^gen/invitecode/$', views.gen_invite_code, name='geninvitecode'),
]

django-sspanel/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('shadowsocks.urls', namespace='shadowsocks')),
    url(r'', include('django.contrib.auth.urls')),    
    url(r'^server/', include('ssserver.urls', namespace='ssserver')),
    url(r'^api/', include('api.urls', namespace='api')),
]

shadowsocks/urls.py
from django.conf.urls import url
from .import views


app_name = "shadowsocks"
urlpatterns = [
    # 网站用户面板
    url(r'^$', views.index, name='index'),
    url(r'^sshelp/$', views.sshelp, name='sshelp'),
    url(r'^ssclient/$', views.ssclient, name='ssclient'),
    url(r'^ssinvite/$', views.ssinvite, name='ssinvite'),
    url(r'^passinvite/(?P<invitecode>[\S]+)/$',
        views.pass_invitecode, name='passinvitecode'),
    # 注册/登录
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.Login_view, name='login'),
    url(r'^logout/$', views.Logout_view, name='logout'),
    # 节点
    url(r'^nodeinfo/$', views.nodeinfo, name='nodeinfo'),
    url(r'^trafficlog/$', views.trafficlog, name='trafficlog'),
    # 用户信息
    url(r'^users/userinfo/$', views.userinfo, name='userinfo'),
    url(r'^users/userinfoedit/$', views.userinfo_edit, name='userinfo_edit'),
    url(r'^checkin/$', views.checkin, name='checkin'),
    #  二维码
    url(r'^qrcode/ssr/(?P<node_id>[0-9]+)$',
        views.get_ssr_qrcode, name='ssrqrcode'),
    url(r'^qrcode/ss/(?P<node_id>[0-9]+)$',
        views.get_ss_qrcode, name='ssqrcode'),
    # 捐赠/充值
    url(r'^donate/$', views.donate, name='donate'),
    url(r'^shop/$', views.shop, name='shop'),
    url(r'^purchaselog/$', views.purchaselog, name='purchaselog'),
    url(r'^purchase/(?P<goods_id>[0-9]+)$', views.purchase, name='purchase'),
    url(r'^chargecenter/$', views.chargecenter, name='chargecenter'),
    url(r'^charge/$', views.charge, name='charge'),
    # 公告
    url(r'^announcement/$', views.announcement, name='announcement'),
    # 工单
    url(r'^ticket/$', views.ticket, name='ticket'),
    url(r'^ticket/create/$', views.ticket_create, name='ticket_create'),
    url(r'^ticket/edit/(?P<pk>[0-9]+)$',
        views.ticket_edit, name='ticket_edit'),
    url(r'^ticket/delete/(?P<pk>[0-9]+)$',
        views.ticket_delete, name='ticket_delete'),
    # 推广相关
    url(r'^affiliate/$', views.affiliate, name='affiliate'),
    url(r'^rebate/record/$', views.rebate_record, name='rebate'),

    # 网站后台面板
    url(r'^backend/$', views.backend_index, name='backend_index'),
    # 邀请码相关
    url(r'^backend/invite/$', views.backend_invite, name='backend_invite'),
    url(r'^invite_gen_code/$', views.gen_invite_code, name='geninvitecode'),
    # 节点相关
    url(r'^backend/nodeinfo$', views.backend_node_info, name='backend_node_info'),
    url(r'^backend/node/delete/(?P<node_id>[0-9]+)$',
        views.node_delete, name='node_delete'),
    url(r'^backend/node/edit/(?P<node_id>[0-9]+)$',
        views.node_edit, name='node_edit'),
    url(r'^backend/node/create/$', views.node_create, name='node_create'),
    # 用户相关
    #url(r'^backend/aliveuser/$', views.backend_Aliveuser, name='alive_user'),
    url(r'^backend/userlist/$', views.backend_UserList, name='user_list'),
    url(r'^backend/user/delete/(?P<pk>[0-9]+)$',
        views.user_delete, name='user_delete'),
    url(r'^backend/user/search/$', views.user_search, name='user_search'),
    url(r'^backend/user/status/$', views.user_status, name='user_status'),
    # 商品充值相关
    url(r'^backend/charge/$', views.backend_charge, name='backend_charge'),
    url(r'^backend/shop$', views.backend_shop, name='backend_shop'),
    url(r'^backend/shop/delete/(?P<pk>[0-9]+)$',
        views.good_delete, name='good_delete'),
    url(r'^backend/good/create/$', views.good_create, name='good_create'),
    url(r'^backend/good/edit/(?P<pk>[0-9]+)$',
        views.good_edit, name='good_edit'),
    url(r'^backend/purchase/history/$',
        views.purchase_history, name='purchase_history'),
    # 支付宝当面付相关:
    url(r'^facepay/qrcode/$', views.gen_face_pay_qrcode, name='facepay_qrcode'),
    # 购买处理逻辑
    url(r'^facepay/(?P<out_trade_no>[0-9]+)',
        views.Face_pay_view, name='facepay_view'),
    # 公告管理相关
    url(r'^backend/anno/$', views.backend_anno, name='backend_anno'),
    url(r'^backend/anno/delete/(?P<pk>[0-9]+)$',
        views.anno_delete, name='anno_delete'),
    url(r'^backend/anno/create/$', views.anno_create, name='anno_create'),
    url(r'^backend/anno/edit/(?P<pk>[0-9]+)$',
        views.anno_edit, name='anno_edit'),
    # 工单相关
    url(r'^backend/ticket/$', views.backend_ticket, name='backend_ticket'),
    url(r'^backend/ticket/edit/(?P<pk>[0-9]+)$',
        views.backend_ticketedit, name='backend_ticketedit'),
]

ssserver/urls.py
from django.conf.urls import url
from .import views


app_name = "ssserver"
urlpatterns = [
    url(r'^changesspass/$', views.ChangeSsPass, name='changesspass'),
    url(r'^user/edit/(?P<pk>[0-9]+)$', views.User_edit, name='user_edit'),
    url(r'^changessmethod/$', views.ChangeSsMethod, name='changessmethod'),
    url(r'^changessprotocol/$', views.ChangeSsProtocol, name='changessprotocol'),
    url(r'^changessobfs/$', views.ChangeSsObfs, name='changessobfs'),
    url(r'^test/$', views.testcheck, name='test'),
    url(r'^clean/zombie/user$', views.clean_zombie_user, name='clean_zombie_user'),
]

templates/sspanel/announcement.html
{% extends 'base.html' %} {% block main %}

<div class="column is-12">
    <section class="hero is-primary is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    公告列表：
                </h1>
                <h2 class="subtitle">
                    站长的小心思全在这了!
                </h2>
            </div>
        </div>
    </section>
</div>

<div class="column is-12">

    <div class="box">
        <div class="content">
            <p class="subtitle">公告记录:</p>
            <table class="table is-striped">
                <thead>
                    <tr>
                        <th>ID:</th>
                        <th>时间:</th>
                        <th>内容:</th>                        
                    </tr>
                </thead>

                {% for record in anno %}
                <tr>
                    <td>#{{ record.pk }}</td>
                    <td>{{ record.time }}</td>
                    <td>{{ record.body |safe }}</td>
                </tr>
                {% empty %}
                <h2 class="subtitle">
                    暂时还没发出公告
                </h2>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock main %}

templates/sspanel/donate.html
{% extends 'base.html' %} {% block main %} {% load static %} {% load ehcofilter %}
<div class="column is-12">
    <section class="hero is-primary is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    捐赠榜：
                </h1>
                <h2 class="subtitle">
                    有你们的支持,才让这里继续下去 谢谢！
                </h2>
            </div>
        </div>
    </section>
</div>
<div class="column is-12">
    <div class="tile is-ancestor">
        <div class="tile is-5 is-vertical is-parent">
            {% if alipay == True %}
            <div class="tile box is-child">
                <p class="subtitle">充值捐赠系统正在内测中...
                    <br>请在下方输入
                    <strong>充值/捐赠金额</strong>
                </p>
                <p>点击提交会弹出
                    <strong>支付宝二维码</strong>
                    <br>扫描二维码确认付款之后
                    <br>账户里会增加对应的金额</p>
                <strong>付完款之后要按红色的确认按钮！</strong>
                <hr>
                <div class="content">
                    <form method="post">
                        {% csrf_token %}
                        <div class="field has-addons">
                            <div class="control">
                                <input name="q" class="input" type="number" placeholder="最低不得小于10元: " required>
                            </div>
                            <div class="control">
                                <button type="submit" class="button is-outlined is-info">提交</button>
                            </div>
                        </div>
                    </form>
                    <hr> {% if out_trade_no %}
                    <figure class="image">
                        <img src="{% url 'shadowsocks:facepay_qrcode' %}">
                    </figure>
                    <p>
                        <strong>付费完成之后请点击确认！</strong>
                    </p>
                    <div class="control">
                        <a class="button is-outlined is-danger" href="{% url 'shadowsocks:facepay_view' out_trade_no %}">确认</a>
                    </div>
                    {% endif %} {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <p class="errorlist">{{ message }}</p>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
            </div>
            {% else %}
            <div class="tile box is-child">
                <p class="subtitle">本站通过充值码进行充值:</p>
                <hr>
                <p class="subtitle">扫描站长支付宝PY获得充值码：</p>
                <figure class="image">
                    <img src="{% static '/img/alipay.png'%}">
                </figure>
            </div>
            {% endif %}
        </div>
        <div class="tile is-7 is-vertical is-parent">
            <div class="tile box is-child">
                <div class="content">
                    <p class="subtitle">在充值界面充值也等同于捐赠，记录会自动同步</p>
                    <table class="table is-striped">
                        <thead>
                            <tr>
                                <th>捐赠人:</th>
                                <th>捐赠金额:</th>
                                <th>捐赠时间:</th>
                            </tr>
                        </thead>
                        {% for donate in donatelist %}
                        <tr>
                            <td>{{ donate.user|mix_name:donate.user }}</td>
                            <td>{{ donate.money }} 元</td>
                            <td>{{ donate.time|date:"m月d日" }}：</td>
                        </tr>
                        {% empty %}
                        <p class="subtitle">
                            居然还没有人捐赠 要喝西北风了
                        </p>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

templates/sspanel/index.html
{% extends 'base.html' %} 
{% block main %}
<div class="columns">
    <div class="column is-one-third">
        <div class="notification is-danger">
            <button class="delete"></button>
            <p class="title is-4">
                好像发现了一个<br/> <br/>了不得的地方！
            </p>
        </div>
    </div>
    <div class="column is-one-third">
        <div class="notification is-success">
            <button class="delete"></button>
            <p class="title is-4">
                是啊是啊！<br/><br/>要进去瞧瞧么？</p>
        </div>
    </div>
    <div class="column is-one-third">
        <div class="notification is-link">
            <button class="delete"></button>
            <p class="title is-4">
                当然要去！<br/><br/>魔王总要救公主！</p>
        </div>
    </div>
</div>
<br/> 
{% if user.is_authenticated %}
<div class="box">
    <p class="title">欢迎小主: {{ user.username }}</p>
    <p class="subtitle">点击下方按钮进入用户中心 </p>
    <button class="button"><a href="{% url 'shadowsocks:userinfo' %}">进入</a></button>
    
</div>
{% else %}
<div class="column box ">
    <h1 class="title"> 注册注册！</h1>
    <h2 class="subtitle">没有账号？快去注册一个吧！</h2>
    <a class="button is-primary is-outlined" href="{% url 'shadowsocks:register' %}">注册</a>
</div>
<br/>
<div class="column box ">
    <h1 class="title"> 登录登录！</h1>
    <h2 class="subtitle">有账号了？登录吧少年！</h2>
    <a class="button is-danger is-outlined" href="{% url 'shadowsocks:login' %}">登录</a>
</div>
<br/> {% endif %} {% endblock main %}

templates/sspanel/login.html
{% extends 'base.html' %} {% block main %}



<div class="column is-12">
    <section class="hero is-info is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    登录界面：
                </h1>
                <h2 class="subtitle">
                    请问需要加点咖啡吗？
                </h2>
            </div>
        </div>
    </section>
</div>




<div class="column is-12">

{% if user.is_authenticated %}
<div class="box">
    <p class="title">欢迎小主: {{ user.username }}</p>
    <p class="subtitle">点击下方按钮进入用户中心 </p>
    <button class="button"><a href="{% url 'shadowsocks:userinfo' %}">进入</a></button>
    
</div>



{% else %}

    <div class="box">
        <h3 class="title">登录:</h3>
        <form class="form" action="{% url 'shadowsocks:login' %}" method="post">
            {% csrf_token %} {{ form.non_field_errors }}

            {% for field in form %}
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
            {% if field.help_text %}
            <p class="help is-danger">{{ field.help_text|safe }}</p>
            {% endif %}
            {% endfor %}
             <hr>
            <div class="field is-grouped">
                <p class="control">
                    <button type="submit" class="button is-primary is-outlined">登录！</button>
                </p>
                {% if USE_SMTP is True %}
                <p class="control">
                    <a class="button is-info is-outlined " href="{% url 'password_reset' %}">忘记密码？</a>
                </p>
                {% endif %}
            </div>
        </form>

    </div>
</div>
{% endif %}
{% endblock main %}

templates/sspanel/register.html
{% extends 'base.html' %} {% block main %}

<div class="column is-12">
    <section class="hero is-info is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    注册界面：
                </h1>
                <h2 class="subtitle">
                    注册需要邀请码喔
                </h2>
            </div>
        </div>
    </section>
</div>




<div class="column is-12">

    <div class="box">
        <h3 class="title">注册:</h3>
        <form class="form" action="{% url 'shadowsocks:register' %}" method="post">
            {% csrf_token %} {% for field in form %}
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }} 
            {% if field.help_text %}
            <p class="help is-danger">{{ field.help_text|safe }}</p>
            {% endif %} {% endfor %}

            <hr>
            <div class="field is-grouped">
                <p class="control">
                    <button type="submit" class="button is-primary is-outlined">注册吧少年！</button>
                </p>
                <p class="control">
                    <a class="button is-info is-outlined " href="{% url 'shadowsocks:login' %}">刚注册过了？</a>
                </p>
            </div>
        </form>

    </div>
</div>



{% endblock main%}

templates/sspanel/ticket.html
{% extends 'base.html' %} {% block main %}

<div class="column is-12">
    <section class="hero is-success">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    工单系统：
                </h1>
                <h2 class="subtitle">
                    有什么问题尽管提！什么时候解决就不知道了！
                </h2>
            </div>
        </div>
    </section>
</div>

<div class="column is-12">
    <div class="box">
        <div class="content">
            <p class="subtitle">我的工单:</p>
            <table class="table is-striped">
                <thead>
                    <tr>
                        <th>操作:</th>
                        <th>ID:</th>
                        <th>时间:</th>
                        <th>标题:</th>
                        <th>状态</th>
                    </tr>
                </thead>

                {% for record in ticket %}
                <tr>
                    <td><a class="button is-info" href="{% url 'shadowsocks:ticket_edit' record.pk %}">查看</a><br>
                        <a class="button is-danger" href="{% url 'shadowsocks:ticket_delete' record.pk %}">删除</a></td>                
                    <td>#{{ record.pk }}</td>
                    <td>{{ record.time }}</td>
                    <td>{{ record.title }}</td>
                    <td>{{ record.status }}</td>
                </tr>
                {% empty %}
                <h2 class="subtitle">
                    暂时还没提过工单呢
                </h2>
                {% endfor %}
            </table>
            <p align="right"><a class="button is-danger is-outlined" href="{% url 'shadowsocks:ticket_create' %}">发起工单</a></p>
        </div>
    </div>
</div>





{% endblock main %}

templates/sspanel/ticketcreate.html
{% extends 'base.html' %} {% block main %}


<div class="column is-12">
    <section class="hero is-light is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    提交新得工单：
                </h1>
                <h2 class="subtitle">
                    格式采用 <strong>Markdown</strong>
                </h2>
            </div>
        </div>
    </section>
</div>

<div class="column is-12">
    <div class="box">

        <form class="form" method="post">
            {% csrf_token %}
            <div class="control is-loading">
                <textarea class="textarea" name="title" type="text" placeholder="标题" rows="1" maxlength="32"></textarea>
                <br>
                <textarea class="textarea" name="body" type="text" placeholder="正文" rows="10"></textarea>
            </div>
            <hr/>
            <div class="is-grouped">
                <button type="submit" class="button is-danger is-outlined ">确认</button>
                <a class="button is-success is-outlined" href="{% url 'shadowsocks:ticket' %}">取消</a>
            </div>
        </form>

</div>

{% endblock main %}

templates/sspanel/userinfo.html
{% extends 'base.html' %} {% block main %} {% if user.is_authenticated %}
<div class="column is-12">
    <section class="hero is-primary is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    用户中心：
                </h1>
                <h2 class="subtitle">
                    这里有你的出生证明....
                </h2>
            </div>
        </div>
    </section>
</div>

<div class="column is-12">

    <div class="tile is-ancestor">

        <div class="tile is-5 is-vertical is-parent">
            <div class="tile box is-child">
                <p class="title">
                    <span class="icon is-large">
                    <i class="fa fa-home"></i>
                    </span> 欢迎小主: {{ user.username }}</p>
                <p class="subtitle is-5">这里的功能还比较少...</p>
                <button class="button"><a href="{% url 'shadowsocks:logout' %}">注销登录</a></button>
                <button class="button"><a href="{% url 'password_change' %}">修改密码</a></button>
                <button class="button"><a><span id="id-change-port">重置端口</span></a></button>
                <hr> 
                <div id="id-checkin-box">
                    {% if user.ss_user.get_check_in %}
                    <p class="subtitle is-5 is-spaced">今天已经签到过了ಠ౪ಠ</p>
                    {% else %}
                    <p class="subtitle is-5 is-spaced"> 今天还没有签到，点一下可以获得{{ min_traffic }}~{{ max_traffic }}流量</p>
                    <br>
                    <button class="button"><a><span id="id-checkin">签到</span></a></button> 
                    {% endif %}
                </div>
            </div>
            <div class="tile box is-child">
                <article class="message">
                    <div class="message-header">
                        <p>最新公告</p>
                    </div>
                    <div class="message-body">
                        {% if anno %} {{ anno.body | safe }} {% else %}
                        <p>暂无公告</p>
                        {% endif %}
                    </div>
                </article>
            </div>
        </div>

        <div class="tile is-7 is-vertical is-parent">

            <div class="tile box is-child">
                <article class="message is-success">
                    <div class="message-header">
                        <p>连接信息</p>
                    </div>
                    <div class="message-body">
                        <li> 端口：<code><span id="port">{{ user.ss_user.port }}</span></code></li>
                        <li> 密码：<code>{{ user.ss_user.password }}</code></li>
                        <li> 加密：<code>{{ user.ss_user.method }}</code></li>
                        <li> 混淆：<code>{{ user.ss_user.protocol }}</code></li>
                        <li> 协议：<code>{{ user.ss_user.obfs }}</code></li>
                        <br>
                        <a class="button is-link " href="{% url 'shadowsocks:nodeinfo' %}">详细节点信息请点击这里</a>
                    </div>
                </article>

                <article class="message is-warning">
                    <div class="message-header">
                        <p>流量信息</p>
                    </div>

                    <div class="message-body">
                        <div class="columns">
                            <div class="column is-4">
                                <li>总量：<code>{{ user.ss_user.get_transfer }}GB </code> </li>
                            </div>
                            <div class="column">
                                <progress class="progress is-success" value="100" max="100"></progress>
                            </div>
                        </div>
                        <div class="columns">
                            <div class="column is-4">
                                <li>剩余：<code>{{ user.ss_user.get_unused_traffic }}GB </code> </li>
                            </div>
                            <div class="column">
                                <progress class="progress is-info" value="{{  remain_traffic }}" max="100"></progress>
                            </div>
                        </div>

                        <div class="columns">
                            <div class="column is-4">
                                <li>使用：<code>{{ user.ss_user.get_used_percentage }}%</code> </li>
                            </div>
                            <div class="column">
                                <progress class="progress is-danger" value="{{  user.ss_user.get_used_percentage }}" max="100"></progress>
                            </div>
                        </div>
                    </div>
                </article>

                <article class="message is-info">
                    <div class="message-header">
                        <p>个人信息</p>
                    </div>
                    <div class="message-body">
                        <li> 余额：<code>{{ user.balance }} 元</code></li>
                        <li> 邮箱：<code>{{ user.email }} </code></li>
                        <li> 等级：<code>{{ user.level }} 级 </code></li>
                        {% if user.ss_user.enable == True %}
                        <li> 状态：<code>正常使用</code></li>
                        {% else %}
                        <li> 状态：<code>失效</code></li>
                        {% endif %}
                        <li> 等级到期时间：<code>{{ user.get_expire_time }} </code></li>
                        <li>上次使用时间: <code>{{ user.ss_user.get_last_use_time|date:"m月d日G点" }}</code></li>

                    </div>
                </article>

            </div>
        </div>
    </div>
</div>

<script>
    // 端口重置Ajax部分
    var ProtButton = $("#id-change-port")
    var changeport = function(){
        url = "{% url 'api:changessport' %}"
        $.getJSON(url,function(results){
            swal(results.title,results.subtitle,results.status)
            port.textContent= results.subtitle.slice(6,-1)
        })
    }
    ProtButton.click(changeport)
    // 签到AJAX部分
    var CheckButton = $("#id-checkin")
    var Checkin = function(){
        url = "{% url 'shadowsocks:checkin' %}"
        $.getJSON(url,function(results){
            swal(results.title,results.subtitle,results.status)
            var box = $("#id-checkin-box")
            box.empty()
            box.append('今天已经签到过了ಠ౪ಠ')
        })
    }
    CheckButton.click(Checkin)
</script>

{% else %}
<p>你还没有登录，请登录 </p>
{% endif %} {% endblock main %}

templates/sspanel/userinfoedit.html
{% extends 'base.html' %} {% block main %}
<div class="column is-12">
    <section class="hero is-primary is-smaill">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    用户资料改写处：
                </h1>
                <h2 class="subtitle">
                    自定义连接信息....
                </h2>
            </div>
        </div>
    </section>
</div>
<div class="column is-12">
    <div class="tile is-ancestor">
         <div class="tile is-6 is-vertical is-parent">
            <div class="tile box is-child">
                <span class="tag is-danger is-large">修改连接密码:</span>
                <hr />
                <p class="subtitle">当前密码:<code>{{ ss_user.password }}</code></p>
                <form class="form" action="{% url 'ssserver:changesspass' %}" method="post">
                    {% csrf_token %}
                    <input type="text" name="password" class="input is-narrow is-danger" required="" id="password">
                    <hr/>
                    <div class="is-grouped">
                        <button type="submit" class="button is-danger is-outlined ">确认修改</button>
                    </div>
                </form>
            </div>
        
            <div class="tile box is-child">
                    <span class="tag is-warning is-large">自定义的加密:</span>
                    <hr />
                    <p class="subtitle">当前加密方式:<code>{{ ss_user.method }}</code></p>
                    <form class="form" action="{% url 'ssserver:changessmethod' %}" method="post">
                        {% csrf_token %}
                        <div class="field is-horizontal">
                            <div class="field-label">
                                <label class="label">method:</label>
                            </div>
                            <div class="field-body">
                                <div class="field">
                                    <div class="control">
                                        <div class="select">
                                            <select name="method">
                                                {% for m in methods %}
                                                <option>{{ m }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="is-grouped">
                            <button type="submit" class="button is-danger is-outlined ">提交</button>
                        </div>
                    </form>
                </div>
        
        </div>

        <div class="tile is-6 is-vertical is-parent">
            <div class="tile box is-child">
                <span class="tag is-success is-large">自定义协议:</span>
                <hr />
                <p class="subtitle">当前协议:<code>{{ ss_user.protocol }}</code></p>
                <form class="form" action="{% url 'ssserver:changessprotocol' %}" method="post">
                    {% csrf_token %}
                    <div class="field is-horizontal">
                        <div class="field-label">
                            <label class="label">protocol:</label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <div class="control">
                                    <div class="select">
                                        <select name="protocol">
                                            {% for p in protocols %}
                                            <option>{{ p }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="is-grouped">
                        <button type="submit" class="button is-danger is-outlined ">提交</button>
                    </div>
                </form>
            </div>
            
            <div class="tile box is-child">
                <span class="tag is-success is-large">自定义混淆:</span>
                <hr />
                <p class="subtitle">当前混淆:<code>{{ ss_user.obfs }}</code></p>
                <form class="form" action="{% url 'ssserver:changessobfs' %}" method="post">
                    {% csrf_token %}
                    <div class="field is-horizontal">
                        <div class="field-label">
                            <label class="label">obfs:</label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <div class="control">
                                    <div class="select">
                                        <select name="obfs">
                                            {% for o in obfss %}                                           
                                            <option>{{ o }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="is-grouped">
                        <button type="submit" class="button is-danger is-outlined ">提交</button>
                    </div>
                </form>
            </div>
        </div>
    </div>




    {% endblock main %}